name: lint text

on: [push, pull_request]

jobs:
  build:
    name: lint text
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
      - name: lint text
        run: npm run lint
